apiVersion: v1    # Kubernetes API version for Deployment Module we are using here
kind: Service     # Kubernetes resource kind we are creating
metadata:
  name: tag-hive-app-b-service   # Name of the service
spec:
  selector:
    app: tag-hive-app-b  #Should be same as Matchlabel app name which is used in Deployment part
  ports:
  - protocol: "TCP"
    port: 5000           # The port that the service is running on in the cluster
    targetPort: 5000     # The port exposed by the service
  type: LoadBalancer     #Type of the service.

---
apiVersion: apps/v1   # Kubernetes API version for Deployment Module we are using here
kind: Deployment      # Kubernetes resource kind we are creating
metadata:
  name: tag-hive-app-b # Name of the Deployment
spec:
  selector:
    matchLabels:
      app: tag-hive-app-b   #Matchlabel app name & labels under template app name should be same
  replicas: 3               # 3 Pods will be run
  template:
    metadata:
      labels:
        app: tag-hive-app-b   #Matchlabel app name & labels under template app name should be same
    spec:
      containers:
      - name: taghive-app-container-b            #Name of the container
        image: taghive-app-b-kubernetes      #Docker Image Name. If Docker Image pushed into Docker hub then we have give docker hub name & repository with Image name here
        imagePullPolicy: Always
        ports:
        - containerPort: 5000